---
title: "draft_report"
author: "Hannah, Jeff, Josh Lin, Pauline"
date: "11/16/2020"
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../reports/") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages('stargazer')
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(janitor)
library(ggplot2)
library(sandwich)
library(lmtest)
library(stargazer)
```

```{r, warning = FALSE}
#combining the two excel sheets 
d <- read_excel("../data/interim/covid-19_v1.xlsx", sheet = "Covid-19", skip=1)
reopen <- read_excel("../data/interim/reopen_CUSP.xlsx", sheet = "Reopening")
total <- merge(d,reopen, by="state")
```

```{r}
#make values numeric 
total$reopen_state_bus = as.numeric(total$reopen_state_bus)
total$reopen_business_statewide = as.numeric(total$reopen_business_statewide)
```


```{r}
total$shelter_in_place = excel_numeric_to_date(total$shelter_in_place)
total$end_shelter_in_place = excel_numeric_to_date(total$end_shelter_in_place)
total$close_nonessential_business = excel_numeric_to_date(total$close_nonessential_business)
total$reopen_business_statewide = excel_numeric_to_date(total$reopen_business_statewide)
total$mandate_facemask = excel_numeric_to_date(total$mandate_facemask)
total$mandate_facemask_employee = excel_numeric_to_date(total$mandate_facemask_employee)
total$end_statewide_mandate_facemask = excel_numeric_to_date(total$end_statewide_mandate_facemask)

total$reopen_restaurants = excel_numeric_to_date(total$reopen_restaurants)
total$reopen_childcare = excel_numeric_to_date(total$reopen_childcare)
total$reopen_business_statewide = excel_numeric_to_date(as.numeric(total$reopen_business_statewide))
total$reopen_gyms = excel_numeric_to_date(total$reopen_gyms)
total$reopen_hair_salons = excel_numeric_to_date(total$reopen_hair_salons)
total$reopen_movie_theaters = excel_numeric_to_date(total$reopen_movie_theaters)
total$`reopen_non-essential_retail` = excel_numeric_to_date(total$`reopen_non-essential_retail`)
total$reopen_religious = excel_numeric_to_date(total$reopen_religious)
total$reopen_state_bus = excel_numeric_to_date(as.numeric(total$reopen_state_bus))
total$reopen_bars = excel_numeric_to_date(total$reopen_bars)
```

```{r}
write_csv(total, file = "../data/interim/covid19+cusp.csv")
```

```{r}
plot(total$`length_ shelter_in_place`, total$cases_per_100k)
total <- total %>% mutate(root_length_shelter = sqrt(`length_ shelter_in_place`))
plot(total$root_length_shelter, total$cases_per_100k)
```
```{r}
#og baseline model

baseline_model <- lm(cases_per_100k ~ `length_ shelter_in_place`, data = total)
summary(baseline_model)
```
```{r}
#11/16 baseline model re: current research q

party_model <- lm(cases_per_100k ~ `length_ shelter_in_place` + political_party_governor, data=total)
summary(party_model)

```
```{r}
#filtering to find number of cases in dem and repub states 
dems <- filter(total, political_party_governor == 'Democratic')
repub <- filter(total, political_party_governor == 'Republican')
dem_cases <- sum(dems$cases_per_100k)
repub_cases <- sum(repub$cases_per_100k)
party_cases<- data.frame(dem_cases, repub_cases)
```


```{r}
#making a barplot of cases for total democratic and republican states 
c1 <- rgb(173,216,230,max = 255, alpha = 200, names = "lt.blue")
c2 <- rgb(255,192,203, max = 255, alpha = 80, names = "lt.pink")
barplot(c(dem_cases, repub_cases), main="State Political Party and Cases",
        ylab = 'Cases per 100K',
        names.arg=c('Democratic', 'Republican'),
        col = c(c1,c2), ylim=c(0, 80000))
```
```{r}
shelterxparty_model <- lm(cases_per_100k ~ `length_ shelter_in_place` + political_party_governor + (`length_ shelter_in_place` * political_party_governor), data=total)
summary(shelterxparty_model)
coeftest(shelterxparty_model, vcov = vcovHC(shelterxparty_model))
```

```{r}
total<- total%>% 
  mutate(
    num_mandate_facemask = 
      ifelse(mandate_facemask == "1899-12-30", 0, 1)
  )
```

```{r}
facemask_model <- lm(cases_per_100k ~ `length_ shelter_in_place` + political_party_governor + num_mandate_facemask, data=total)
summary(facemask_model)
```
```{r}
coeftest(facemask_model, vcov = vcovHC(facemask_model))
```

```{r, warning=FALSE}
se.model1 = coeftest(party_model, vcov = vcovHC)[ , "Std. Error"]
se.model2 = coeftest(shelterxparty_model, vcov = vcovHC)[ , "Std. Error"]
se.model3 = coeftest(facemask_model, vcov = vcovHC)[ , "Std. Error"]

stargazer(party_model, shelterxparty_model, facemask_model, type = "text", omit.stat = "f", se = list(se.model3), star.cutoffs = c(0.05, 0.01, 0.001), title = "Table 1: The relationship between cases per 100k and state political party")
```

